services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    ports:
      - "3379:2379"
      - "3380:2380"
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.232.12:3379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=etcd
    volumes:
      - ./components/etcd/data:/bitnami/etcd/data
      - ./components/etcd/logs:/bitnami/etcd/logs
    networks:
      hnz-chat:

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 16379:6379
    volumes:
      - ./components/redis/data:/data
    #  - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
      - ./components/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      hnz-chat:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 13306:3306
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: hnz-chat
      restart: always
    networks:
      hnz-chat:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 47017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hnz-chat
    volumes:
      - ./components/mongo/data:/data/db
      - /etc/localtime:/etc/localtime
    restart: always
    networks:
      hnz-chat:
networks:
  hnz-chat:
      driver: bridge