services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    ports:
      - "3379:2379"
      - "3380:2380"
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.232.12:3379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=etcd
    volumes:
      - ./components/etcd/data:/bitnami/etcd/data
      - ./components/etcd/logs:/bitnami/etcd/logs
    networks:
      hnz-chat:

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 16379:6379
    volumes:
      - ./components/redis/data:/data
    #  - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
      - ./components/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      hnz-chat:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 13306:3306
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: hnz-chat
      restart: always
    networks:
      hnz-chat:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 47017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hnz-chat
    volumes:
      - ./components/mongo/data:/data/db
      - /etc/localtime:/etc/localtime
    restart: always
    networks:
      hnz-chat:
  #    zookeeper
  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181
    container_name: zookeeper
    volumes:
      - /etc/localtime:/etc/localtime
      - ./components/zookeeper/data:/data
      - ./components/zookeeper/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOO_MAX_CLIENT_CNXNS: 0  # 禁用连接数限制
      KAFKA_HEAP_OPTS: "-Xmx1g -Xms1g"  # 内存分配
    ulimits:
      nofile: 65536  # 文件描述符限制
    restart: always
    networks:
      hnz-chat:

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ws2ms_chat:8:1,ms2ps_chat:8:1,msg_to_mongo:8:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://192.168.232.12:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    networks:
      hnz-chat:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

    restart: always
    networks:
      hnz-chat:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    volumes:
      - /etc/localtime:/etc/localtime
      - ./components/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
    restart: always
    environment:
      - 'cluster.name=elasticsearch'
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
    networks:
      hnz-chat:

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: kibana
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./components/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    networks:
      hnz-chat:

networks:
  hnz-chat:
    driver: bridge