// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"go-chat/apps/im/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 根据用户获取聊天记录
				Method:  http.MethodGet,
				Path:    "/chatlog",
				Handler: getChatLogHandler(serverCtx),
			},
			{
				// 获取聊天记录已读未读记录
				Method:  http.MethodGet,
				Path:    "/chatlog/readRecords",
				Handler: getChatLogReadRecordsHandler(serverCtx),
			},
			{
				// 获取会话列表
				Method:  http.MethodGet,
				Path:    "/conversation",
				Handler: getConvesationsHandler(serverCtx),
			},
			{
				// 更新会话列表
				Method:  http.MethodPut,
				Path:    "/conversation",
				Handler: putConvesationsHandler(serverCtx),
			},
			{
				// 建立会话列表
				Method:  http.MethodPost,
				Path:    "/setup/conversations",
				Handler: setUpUserConvesationHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/im"),
	)
}
