// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ChatLog struct {
	Id             string `json:"id,omitempty"`
	ConversationId string `json:"conversationId,omitempty"`
	ReceiveId      string `json:"receiveId,omitempty"`
	MsgType        int32  `json:"msgType,omitempty"`
	MsgContent     string `json:"msgContent,omitempty"`
	ChatType       int32  `json:"chatType,omitempty"`
	SendTime       int64  `json:"sendTime,omitempty"`
}

type ChatLogReq struct {
	MsgId          string `json:"msgId"`
	ConversationId string `json:"conversationId"`
	StartSendTime  int64  `json:"startSendTime,omitempty"`
	EndSendTime    int64  `json:"endSendTime,omitempty"`
	Count          int64  `json:"count,omitempty"`
}

type ChatLogResp struct {
	List []*ChatLog `json:"list"`
}

type Conversation struct {
	ConversationId string `json:"conversationId,omitempty"`
	ChatType       int32  `json:"chatType,omitempty"`
	IsShow         bool   `json:"isShow,omitempty"`
	Seq            int64  `json:"seq,omitempty"`
	Read           int32  `json:"read,omitempty"`
}

type GetChatLogReadRecordsReq struct {
	MsgId string `json:"msgId"`
}

type GetChatLogReadRecordsResp struct {
	Reads   []string `json:"reads"`
	UnReads []string `json:"unReads"`
}

type GetConvesationsReq struct {
}

type GetConvesationsResp struct {
	ConversationList map[string]*Conversation `json:"conversationList"`
}

type PutConvesationsReq struct {
	ConversationList map[string]*Conversation `json:"conversationList"`
}

type PutConvesationsResp struct {
}

type SetUpUserConvesationReq struct {
	SendId    string `json:"sendId,omitempty"`
	ReceiveId string `json:"receiveId,omitempty"`
	ChatType  int32  `json:"chatType,omitempty"`
}

type SetUpUserConvesationResp struct {
}
