### 构建容器 ###
FROM alpine:3.20

# 添加时区处理
RUN echo -e "https://mirrors.aliyun.com/alpine/v3.20/main\nhttps://mirrors.aliyun.com/alpine/v3.20/community" > /etc/apk/repositories && \
    apk update && \
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone \
    ENV TZ Asia/Shanghai

# 构建参数
ARG SERVER_NAME=im
ARG SERVER_TYPE=rpc
#ARG SERVER_VERSION=1.0.0

# 设置环境变量
ENV RUN_BIN bin/${SERVER_NAME}-${SERVER_TYPE}
ENV RUN_CONF /${SERVER_NAME}/conf/${SERVER_NAME}.yaml

# 命令 左边是宿主机的目录，右边是容器的目录
RUN mkdir /$SERVER_NAME && mkdir /$SERVER_NAME/bin && mkdir /$SERVER_NAME/conf

# 复制编译后的二进制文件
COPY ./bin/${SERVER_NAME}-${SERVER_TYPE} /$SERVER_NAME/bin/

# 复制配置文件
COPY ./apps/$SERVER_NAME/$SERVER_TYPE/etc/dev/$SERVER_NAME.yaml /$SERVER_NAME/conf/

# 为二进制文件提供执行权限
RUN chmod +x /$SERVER_NAME/bin/${SERVER_NAME}-${SERVER_TYPE}

WORKDIR /$SERVER_NAME


ENTRYPOINT $RUN_BIN -f $RUN_CONF